### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by bho10** [Haventec/haventec-authenticate-sample-app#1]
Hi,

I tried running your app but it seems to be a few dependencies missing in your package.json
```
@angular/tsc-wrapped
localforage
localforage-cordovasqlitedriver
base64-js
ieee754
```
:)

**Comment by rachelcosterhaventec** [comment]
Hi there,

Thank you so much for raising this issue. We have updated our package.json and package-lock.json to resolve this issue. We recommend using at least node.js version 8.

Please feel free to raise any other issues that you may find in the future.

- Haventec
